url: "https://andresanz.com" 
baseurl: ""
title: "Andr&eacute; Sanz"
shortname: "andresanz.com"
description: "A highly experienced Information Technology Leader with a proven track record of success in managing critical IT operations, business-focused projects & customer relationships. Critical thinker, leader and communicator who can inspire changes in people and drive changes in process & technology to achieve great results. A proven track record of delivering in areas including: Client Technology, Technology Training, Service Management, Service Delivery, Program Management & Project Delivery"
tagline: "the home of Andr&eacute; Sanz"

google_analytics: ???

google_search: ???

# ReCaptcha contact form variables
recaptchaSecret: ???
data-sitekey: ???

plugins:
    - jekyll-seo-tag 
    - jekyll-feed
  
sass:
  style: expanded
  sass_dir: _sass
  sourcemap: never
  
permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
include:
 - ".htaccess"

exclude: 
 - ".notes"
 - "Gemfile"
 - "update"
 - "newdraft"
 - "gitpush"
 - "rundevserver"
 - "README.md"
 - "*/_exclude/"
 - "*txt.html" 
 - "*/.backup/"
 
author:
  name: Andre Sanz
  url: https://andresanz.com/

